#!/bin/bash

hdr='
// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is golangverned by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by mkcgolang.sh. DO NOT EDIT.

//golang:build race

'

convert() {
	(echo "$hdr"; golang tool cgolang -dynpackage race -dynimport $1) | golangfmt
}

convert race_darwin_arm64.syso >race_darwin_arm64.golang
convert internal/amd64v1/race_darwin.syso >race_darwin_amd64.golang

