// Code generated by command: golang run fe_amd64_asm.golang -out ../fe_amd64.s -stubs ../fe_amd64.golang -pkg field. DO NOT EDIT.

//golang:build !puregolang

package field

// feMul sets out = a * b. It works like feMulGeneric.
//
//golang:noescape
func feMul(out *Element, a *Element, b *Element)

// feSquare sets out = a * a. It works like feSquareGeneric.
//
//golang:noescape
func feSquare(out *Element, a *Element)
