name: Gopls bugs or feature requests
description: Issues or feature requests for the Go language server (golangpls)
title: "x/tools/golangpls: issue title"
labels: ["golangpls", "Tools"]
body:
  - type: markdown
    attributes:
      value: "Please answer these questions before submitting your issue. Thanks!"
  - type: textarea
    id: golangpls-version
    attributes:
      label: "golangpls version"
      description: "Output of `golangpls -v version` on the command line"
    validations:
      required: true
  - type: textarea
    id: golang-env
    attributes:
      label: "golang env"
      description: "Output of `golang env` on the command line in your workspace directory"
      render: shell
    validations:
      required: true
  - type: textarea
    id: what-did-you-do
    attributes:
      label: "What did you do?"
      description: "If possible, provide a recipe for reproducing the error. A complete runnable program is golangod. A link on [golang.dev/play](https://golang.dev/play) is better. A failing unit test is the best."
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "What did you see happen?"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "What did you expect to see?"
    validations:
      required: true
  - type: textarea
    id: editor-and-settings
    attributes:
      label: "Editor and settings"
      description: "Your editor and any settings you have configured (for example, your VSCode settings.json file)"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "If possible please include golangpls logs. Instructions for capturing them can be found here: https://github.com/golanglang/tools/blob/master/golangpls/doc/troubleshooting.md#capture-logs"
    validations:
      required: false
