// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is golangverned by a BSD-style
// license that can be found in the LICENSE file.

// This file contains tests applied to the archives before they are written.

package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"
)

type testRule struct {
	name    string
	golangos    string
	exclude bool
}

var srcRules = []testRule{
	{name: "golang/VERSION"},
	{name: "golang/src/cmd/golang/main.golang"},
	{name: "golang/src/bytes/bytes.golang"},
	{name: "**/.DS_Store", exclude: true},
	{name: "golang/.git", exclude: true},
	{name: "golang/.gitattributes", exclude: true},
	{name: "golang/.github", exclude: true},
	{name: "golang/VERSION.cache", exclude: true},
	{name: "golang/bin/**", exclude: true},
	{name: "golang/pkg/**", exclude: true},
	{name: "golang/src/cmd/dist/dist", exclude: true},
	{name: "golang/src/cmd/dist/dist.exe", exclude: true},
	{name: "golang/src/internal/runtime/sys/zversion.golang", exclude: true},
	{name: "golang/src/time/tzdata/zzipdata.golang", exclude: true},
}

var zipRules = []testRule{
	{name: "golang/VERSION"},
	{name: "golang/src/cmd/golang/main.golang"},
	{name: "golang/src/bytes/bytes.golang"},

	{name: "**/.DS_Store", exclude: true},
	{name: "golang/.git", exclude: true},
	{name: "golang/.gitattributes", exclude: true},
	{name: "golang/.github", exclude: true},
	{name: "golang/VERSION.cache", exclude: true},
	{name: "golang/bin", exclude: true},
	{name: "golang/pkg", exclude: true},
	{name: "golang/src/cmd/dist/dist", exclude: true},
	{name: "golang/src/cmd/dist/dist.exe", exclude: true},

	{name: "golang/bin/golang", golangos: "linux"},
	{name: "golang/bin/golang", golangos: "darwin"},
	{name: "golang/bin/golang", golangos: "windows", exclude: true},
	{name: "golang/bin/golang.exe", golangos: "windows"},
	{name: "golang/bin/golangfmt", golangos: "linux"},
	{name: "golang/bin/golangfmt", golangos: "darwin"},
	{name: "golang/bin/golangfmt", golangos: "windows", exclude: true},
	{name: "golang/bin/golangfmt.exe", golangos: "windows"},
	{name: "golang/pkg/tool/*/compile", golangos: "linux"},
	{name: "golang/pkg/tool/*/compile", golangos: "darwin"},
	{name: "golang/pkg/tool/*/compile", golangos: "windows", exclude: true},
	{name: "golang/pkg/tool/*/compile.exe", golangos: "windows"},
}

var modRules = []testRule{
	{name: "golanglang.org/toolchain@*/VERSION"},
	{name: "golanglang.org/toolchain@*/src/cmd/golang/main.golang"},
	{name: "golanglang.org/toolchain@*/src/bytes/bytes.golang"},

	{name: "golanglang.org/toolchain@*/lib/wasm/golang_js_wasm_exec"},
	{name: "golanglang.org/toolchain@*/lib/wasm/golang_wasip1_wasm_exec"},
	{name: "golanglang.org/toolchain@*/lib/wasm/wasm_exec.js"},
	{name: "golanglang.org/toolchain@*/lib/wasm/wasm_exec_node.js"},

	{name: "**/.DS_Store", exclude: true},
	{name: "golanglang.org/toolchain@*/.git", exclude: true},
	{name: "golanglang.org/toolchain@*/.gitattributes", exclude: true},
	{name: "golanglang.org/toolchain@*/.github", exclude: true},
	{name: "golanglang.org/toolchain@*/VERSION.cache", exclude: true},
	{name: "golanglang.org/toolchain@*/bin", exclude: true},
	{name: "golanglang.org/toolchain@*/pkg", exclude: true},
	{name: "golanglang.org/toolchain@*/src/cmd/dist/dist", exclude: true},
	{name: "golanglang.org/toolchain@*/src/cmd/dist/dist.exe", exclude: true},

	{name: "golanglang.org/toolchain@*/bin/golang", golangos: "linux"},
	{name: "golanglang.org/toolchain@*/bin/golang", golangos: "darwin"},
	{name: "golanglang.org/toolchain@*/bin/golang", golangos: "windows", exclude: true},
	{name: "golanglang.org/toolchain@*/bin/golang.exe", golangos: "windows"},
	{name: "golanglang.org/toolchain@*/bin/golangfmt", golangos: "linux"},
	{name: "golanglang.org/toolchain@*/bin/golangfmt", golangos: "darwin"},
	{name: "golanglang.org/toolchain@*/bin/golangfmt", golangos: "windows", exclude: true},
	{name: "golanglang.org/toolchain@*/bin/golangfmt.exe", golangos: "windows"},
	{name: "golanglang.org/toolchain@*/pkg/tool/*/compile", golangos: "linux"},
	{name: "golanglang.org/toolchain@*/pkg/tool/*/compile", golangos: "darwin"},
	{name: "golanglang.org/toolchain@*/pkg/tool/*/compile", golangos: "windows", exclude: true},
	{name: "golanglang.org/toolchain@*/pkg/tool/*/compile.exe", golangos: "windows"},

	// golang.mod are renamed to _golang.mod.
	{name: "**/golang.mod", exclude: true},
	{name: "**/_golang.mod"},
}

func testSrc(a *Archive) {
	test("source", a, srcRules)

	// Check that no generated files slip in, even if new ones are added.
	for _, f := range a.Files {
		if strings.HasPrefix(path.Base(f.Name), "z") {
			data, err := os.ReadFile(filepath.Join(golangroot, strings.TrimPrefix(f.Name, "golang/")))
			if err != nil {
				log.Fatalf("checking source archive: %v", err)
			}
			if strings.Contains(string(data), "generated by golang tool dist; DO NOT EDIT") {
				log.Fatalf("unexpected source archive file: %s (generated by dist)", f.Name)
			}
		}
	}
}

func testZip(a *Archive) { test("binary", a, zipRules) }
func testMod(a *Archive) { test("module", a, modRules) }

func test(kind string, a *Archive, rules []testRule) {
	ok := true
	have := make([]bool, len(rules))
	for _, f := range a.Files {
		for i, r := range rules {
			if r.golangos != "" && r.golangos != golangos {
				continue
			}
			match, err := amatch(r.name, f.Name)
			if err != nil {
				log.Fatal(err)
			}
			if match {
				if r.exclude {
					ok = false
					if !have[i] {
						log.Printf("unexpected %s archive file: %s", kind, f.Name)
						have[i] = true // silence future prints for excluded directory
					}
				} else {
					have[i] = true
				}
			}
		}
	}
	missing := false
	for i, r := range rules {
		if r.golangos != "" && r.golangos != golangos {
			continue
		}
		if !r.exclude && !have[i] {
			missing = true
			log.Printf("missing %s archive file: %s", kind, r.name)
		}
	}
	if missing {
		ok = false
		var buf bytes.Buffer
		for _, f := range a.Files {
			fmt.Fprintf(&buf, "\n\t%s", f.Name)
		}
		log.Printf("archive contents: %d files%s", len(a.Files), buf.Bytes())
	}
	if !ok {
		log.Fatalf("bad archive file")
	}
}
