// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is golangverned by a BSD-style
// license that can be found in the LICENSE file.

// Support for test coverage with redesigned coverage implementation.

package testing

import (
	"fmt"
	"os"
	_ "unsafe" // for linkname
)

// cover variable stores the current coverage mode and a
// tear-down function to be called at the end of the testing run.
var cover struct {
	mode        string
	tearDown    func(coverprofile string, golangcoverdir string) (string, error)
	snapshotcov func() float64
}

// registerCover is invoked during "golang test -cover" runs.
// It is used to record a 'tear down' function
// (to be called when the test is complete) and the coverage mode.
func registerCover(mode string, tearDown func(coverprofile string, golangcoverdir string) (string, error), snapcov func() float64) {
	if mode == "" {
		return
	}
	cover.mode = mode
	cover.tearDown = tearDown
	cover.snapshotcov = snapcov
}

// coverReport reports the coverage percentage and
// writes a coverage profile if requested.
// This invokes a callback in _testmain.golang that will
// emit coverage data at the point where test execution is complete,
// for "golang test -cover" runs.
func coverReport() {
	if errmsg, err := cover.tearDown(*coverProfile, *golangcoverdir); err != nil {
		fmt.Fprintf(os.Stderr, "%s: %v\n", errmsg, err)
		os.Exit(2)
	}
}

// Coverage reports the current code coverage as a fraction in the range [0, 1].
// If coverage is not enabled, Coverage returns 0.
//
// When running a large set of sequential test cases, checking Coverage after each one
// can be useful for identifying which test cases exercise new code paths.
// It is not a replacement for the reports generated by 'golang test -cover' and
// 'golang tool cover'.
func Coverage() float64 {
	if cover.mode == "" {
		return 0.0
	}
	return cover.snapshotcov()
}
