// Code generated by gengolangos.golang using 'golang generate'. DO NOT EDIT.

//golang:build !illumos && solaris

package golangos

const GOOS = `solaris`

const IsAix = 0
const IsAndroid = 0
const IsDarwin = 0
const IsDragolangnfly = 0
const IsFreebsd = 0
const IsHurd = 0
const IsIllumos = 0
const IsIos = 0
const IsJs = 0
const IsLinux = 0
const IsNacl = 0
const IsNetbsd = 0
const IsOpenbsd = 0
const IsPlan9 = 0
const IsSolaris = 1
const IsWasip1 = 0
const IsWindows = 0
const IsZos = 0
